on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master


name: Pandoc

jobs:
  Pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-pandoc@v1
    with:
        pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
    - run: echo "# Test" | pandoc -t html